// <auto-generated />
using System;
using MarinaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarinaApi.Migrations
{
    [DbContext(typeof(MarinaDbContext))]
    partial class MarinaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarcoRegata", b =>
                {
                    b.Property<long>("BarcosId")
                        .HasColumnType("bigint");

                    b.Property<long>("RegatasId")
                        .HasColumnType("bigint");

                    b.HasKey("BarcosId", "RegatasId");

                    b.HasIndex("RegatasId");

                    b.ToTable("BarcoRegata", (string)null);
                });

            modelBuilder.Entity("MarinaApi.Models.Amarre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("BarcoId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Electricidad")
                        .HasColumnType("bit");

                    b.Property<int>("Longitud")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<int>("Profundidad")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("BarcoId")
                        .IsUnique()
                        .HasFilter("[BarcoId] IS NOT NULL");

                    b.ToTable("Amarres");
                });

            modelBuilder.Entity("MarinaApi.Models.Barco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("Eslora")
                        .HasColumnType("int");

                    b.Property<int>("Manga")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Barcos");
                });

            modelBuilder.Entity("MarinaApi.Models.Organizador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Organizadores");
                });

            modelBuilder.Entity("MarinaApi.Models.Regata", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Distancia")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date");

                    b.Property<string>("Lugar")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long?>("OrganizadorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrganizadorId");

                    b.ToTable("Regatas");
                });

            modelBuilder.Entity("MarinaApi.Models.Tripulante", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("BarcoId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BarcoId");

                    b.ToTable("Tripulantes");
                });

            modelBuilder.Entity("BarcoRegata", b =>
                {
                    b.HasOne("MarinaApi.Models.Barco", null)
                        .WithMany()
                        .HasForeignKey("BarcosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarinaApi.Models.Regata", null)
                        .WithMany()
                        .HasForeignKey("RegatasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MarinaApi.Models.Amarre", b =>
                {
                    b.HasOne("MarinaApi.Models.Barco", "Barco")
                        .WithOne("Amarre")
                        .HasForeignKey("MarinaApi.Models.Amarre", "BarcoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Barco");
                });

            modelBuilder.Entity("MarinaApi.Models.Regata", b =>
                {
                    b.HasOne("MarinaApi.Models.Organizador", "Organizador")
                        .WithMany("Regatas")
                        .HasForeignKey("OrganizadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("MarinaApi.Models.Tripulante", b =>
                {
                    b.HasOne("MarinaApi.Models.Barco", "Barco")
                        .WithMany("Tripulantes")
                        .HasForeignKey("BarcoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Barco");
                });

            modelBuilder.Entity("MarinaApi.Models.Barco", b =>
                {
                    b.Navigation("Amarre");

                    b.Navigation("Tripulantes");
                });

            modelBuilder.Entity("MarinaApi.Models.Organizador", b =>
                {
                    b.Navigation("Regatas");
                });
#pragma warning restore 612, 618
        }
    }
}
